//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKHUYENMAI
    {
        public string MAKM { get; set; }
        public string MASACH { get; set; }
        public int SOLUONGGIAM { get; set; }
        public string GHICHU { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
