//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        public string MAPT { get; set; }
        public string MAKH { get; set; }
        public System.DateTime NGAYTHU { get; set; }
        public Nullable<decimal> TIENNO { get; set; }
        public Nullable<decimal> TIENTHU { get; set; }
        public Nullable<decimal> TIENTHUA { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
