//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        public int MAQD { get; set; }
        public Nullable<int> NHAPTOITHIEU { get; set; }
        public Nullable<int> NHAPTOIDA { get; set; }
        public Nullable<int> TONTOITHIEU { get; set; }
        public Nullable<decimal> NOTOIDA { get; set; }
    }
}
