//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class CTKHUYENMAI:BaseViewModel
    {
        private string _MAKM;
        public string MAKM { get { return _MAKM; } set { _MAKM = value; OnPropertyChanged(); } }
        private string _MASACH;
        public string MASACH { get { return _MASACH; } set { _MASACH = value; OnPropertyChanged(); } }
        private int _SOLUONGGIAM;
        public int SOLUONGGIAM { get { return _SOLUONGGIAM; } set { _SOLUONGGIAM = value; OnPropertyChanged(); } }
        public string GHICHU { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
