//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUAN_LI_NHA_SACHEntities : DbContext
    {
        public QUAN_LI_NHA_SACHEntities()
            : base("name=QUAN_LI_NHA_SACHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHOADON> CTHOADONs { get; set; }
        public virtual DbSet<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISACH> LOAISACHes { get; set; }
        public virtual DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }
        public virtual DbSet<PHIEUNHAPSACH> PHIEUNHAPSACHes { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
        public virtual DbSet<QUYDINH> QUYDINHs { get; set; }
    
        public virtual ObjectResult<USP_BAOCAODOANHTHU_Result> USP_BAOCAODOANHTHU(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BAOCAODOANHTHU_Result>("USP_BAOCAODOANHTHU", dateParameter);
        }
    
        public virtual ObjectResult<USP_BAOCAOCHIPHI_Result> USP_BAOCAOCHIPHI(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_BAOCAOCHIPHI_Result>("USP_BAOCAOCHIPHI", dateParameter);
        }
    
        public virtual ObjectResult<USP_DOANHTHUSACHTRONGTHANG_Result> USP_DOANHTHUSACHTRONGTHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DOANHTHUSACHTRONGTHANG_Result>("USP_DOANHTHUSACHTRONGTHANG");
        }
    
        public virtual ObjectResult<string> USP_SACHBANCHAYTRONGTHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_SACHBANCHAYTRONGTHANG");
        }
    }
}
