//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using ViewModel;

    public partial class PHIEUNHAPSACH: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAPSACH()
        {
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
        }

        private bool _isEnabledListView;
        public bool IsEnabledListView { get { return _isEnabledListView; } set { _isEnabledListView = value; OnPropertyChanged(); } }

        private int _MAPHIEUNHAP;
        public int MAPHIEUNHAP { get { return _MAPHIEUNHAP; } set { _MAPHIEUNHAP = value; OnPropertyChanged(); } }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        private Nullable<decimal> _TONGCHI;
        public Nullable<decimal> TONGCHI { get { return _TONGCHI; } set { _TONGCHI = value; OnPropertyChanged(); } }

        private System.DateTime _NGAYNHAP;
        public System.DateTime NGAYNHAP { get { return _NGAYNHAP; } set { _NGAYNHAP = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
    }
}
