//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class PHIEUTHUTIEN:BaseViewModel
    {
        private string _MAPT;
        public string MAPT { get { return _MAPT; } set { _MAPT = value; OnPropertyChanged(); } }
        private string _MAKH;
        public string MAKH { get { return _MAKH; } set { _MAKH = value; OnPropertyChanged(); } }
        private System.DateTime _NGAYTHU;
        public System.DateTime NGAYTHU { get { return _NGAYTHU; } set { _NGAYTHU = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TIENNO;
        public Nullable<decimal> TIENNO { get { return _TIENNO; } set { _TIENNO = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TIENTHU;
        public Nullable<decimal> TIENTHU { get { return _TIENTHU; } set { _TIENTHU = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TIENTHUA;
        public Nullable<decimal> TIENTHUA { get { return _TIENTHUA; } set { _TIENTHUA = value; OnPropertyChanged(); } }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
