//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
        }
    
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string MALOAISACH { get; set; }
        public string TACGIA { get; set; }
        public string MANXB { get; set; }
        public int SOLUONGHIENTAI { get; set; }
        public byte[] HINHANH { get; set; }
        public decimal GIANHAP { get; set; }
        public decimal GIABAN { get; set; }
        public string NOIDUNG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
    }
}
