//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class SACH: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
        }

        public NHAXUATBAN NXB { get; set; }
        public LOAISACH LoaiSach { get; set; }

        private string _MASACH;
        public string MASACH { get { return _MASACH; } set { _MASACH = value; OnPropertyChanged(); } }

        private string _TENSACH;
        public string TENSACH { get { return _TENSACH; } set { _TENSACH = value; OnPropertyChanged(); } }

        private string _MALOAISACH;
        public string MALOAISACH { get { return _MALOAISACH; } set { _MALOAISACH = value; OnPropertyChanged(); } }

        private string _TACGIA;
        public string TACGIA { get { return _TACGIA; } set { _TACGIA = value; OnPropertyChanged(); } }

        private string _MANXB;
        public string MANXB { get { return _MANXB; } set { _MANXB = value; OnPropertyChanged(); } }

        private Nullable<int> _SOLUONGHIENTAI;
        public Nullable<int> SOLUONGHIENTAI { get { return _SOLUONGHIENTAI; } set { _SOLUONGHIENTAI = value; OnPropertyChanged(); } }

        private byte[] _HINHANH;
        public byte[] HINHANH { get { return _HINHANH; } set { _HINHANH = value; OnPropertyChanged(); } }

        private decimal _GIANHAP;
        public decimal GIANHAP { get { return _GIANHAP; } set { _GIANHAP = value; OnPropertyChanged(); } }

        private decimal _GIABAN;
        public decimal GIABAN { get { return _GIABAN; } set { _GIABAN = value; OnPropertyChanged(); } }

        public string NOIDUNG { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual LOAISACH LOAISACH { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
    }
}
