//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreManagerment.Model
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class TAIKHOAN: BaseViewModel
    {
        public int MATK { get; set; }
        public string TENTK { get; set; }
        public string MATKHAU { get; set; }
        public string TENHIENTHI { get; set; }
        public byte[] HINHANH { get; set; }
        public int LOAITK { get; set; }
    }
}
