CREATE DATABASE QUAN_LI_NHA_SACH
GO
USE QUAN_LI_NHA_SACH

SET DATEFORMAT DMY
 GO
CREATE TABLE KHACHHANG(
MAKH CHAR(5) NOT NULL,
TENKH NVARCHAR(50) NOT NULL,
DIACHI NVARCHAR(100) NOT NULL,
SODIENTHOAI CHAR(11),
EMAIL NVARCHAR(100),
TIENNO MONEY NOT NULL,
DIEMTICHLUY INT NOT NULL
PRIMARY KEY (MAKH))

GO

CREATE TABLE HOADON(
SOHD INT NOT NULL IDENTITY,
MAKH CHAR(5) NOT NULL,
NGAYHD DATETIME NOT NULL,
TONGTIEN MONEY NOT NULL DEFAULT 0,
PRIMARY KEY (SOHD))
ALTER TABLE dbo.HOADON ADD TIENTHUA MONEY DEFAULT 0
ALTER TABLE dbo.HOADON ADD TIENNHAN MONEY DEFAULT 0

GO
--CREATE TABLE KHUYENMAI(
--MAKM INT NOT NULL IDENTITY(1, 1),
--TENKM NVARCHAR(40) NOT NULL,
--NGAYBD DATETIME NOT NULL,
--NGAYKT DATETIME NOT NULL
--PRIMARY KEY (MAKM))

GO
--CREATE TABLE CTKHUYENMAI(
--MAKM INT NOT NULL,
--MALOAIKH CHAR(4) NOT NULL,
--MALOAISACH INT NOT NULL,
--SOLUONGGIAM INT NOT NULL,
--GHICHU NVARCHAR(100)
--PRIMARY KEY (MAKM, MALOAIKH, MALOAISACH))

GO
CREATE TABLE LOAISACH(
MALOAISACH CHAR(5) NOT NULL,
TENLOAISACH NVARCHAR(30) NOT NULL,
CHUDE NVARCHAR(30) 
PRIMARY KEY (MALOAISACH))

GO
CREATE TABLE SACH(
MASACH CHAR(5) NOT NULL,
TENSACH NVARCHAR(50) NOT NULL,
MALOAISACH CHAR(5) NOT NULL,
TACGIA NVARCHAR(50) NOT NULL,
MANXB CHAR(5) NOT NULL,
SOLUONGHIENTAI INT,
HINHANH IMAGE,
GIANHAP MONEY NOT NULL,
GIABAN MONEY NOT NULL,
NOIDUNG NVARCHAR(100)
PRIMARY KEY (MASACH))

GO


CREATE TABLE CTHOADON(
SOHD INT NOT NULL,
MASACH CHAR(5) NOT NULL,
SOLUONG INT NOT NULL,
THANHTIEN MONEY NOT NULL DEFAULT 0 
PRIMARY KEY (SOHD, MASACH))
ALTER TABLE CTHOADON ADD GIABAN MONEY NOT NULL

GO
CREATE TABLE TAIKHOAN(
TENTK NVARCHAR(30) NOT NULL PRIMARY KEY,
MATKHAU CHAR(30) NOT NULL,
TENHIENTHI NVARCHAR(50) NOT NULL,
HINHANH IMAGE,
LOAITK INT NOT NULL
)

GO

CREATE TABLE PHIEUNHAPSACH(
MAPHIEUNHAP INT NOT NULL IDENTITY,
TONGCHI MONEY, 
NGAYNHAP DATETIME NOT NULL
PRIMARY KEY (MAPHIEUNHAP))
GO

CREATE TABLE CTPHIEUNHAP(
MAPHIEUNHAP INT NOT NULL,
MASACH CHAR(5) NOT NULL,
SOLUONG INT NOT NULL,
DONGIA MONEY NOT NULL,
THANHTIEN MONEY --DONGIA*PHIEUNHAP
PRIMARY KEY (MAPHIEUNHAP, MASACH))

GO
CREATE TABLE NHAXUATBAN(
MANXB CHAR(5) NOT NULL,
TENNXB NVARCHAR(30) NOT NULL,
DIACHI NVARCHAR(50)
PRIMARY KEY (MANXB))
GO

CREATE TABLE PHIEUTHUTIEN(
MAPT CHAR(5) PRIMARY KEY,
MAKH CHAR(5) NOT NULL,
NGAYTHU DATETIME NOT NULL,
TIENNO MONEY,
TIENTHU MONEY,
TIENTHUA MONEY
)
CREATE TABLE QUYDINH
(
	MAQD INT IDENTITY PRIMARY KEY,
	NHAPTOITHIEU INT DEFAULT 5,
	NHAPTOIDA INT DEFAULT 500,
	TONTOITHIEU INT DEFAULT 1,
	NOTOIDA MONEY DEFAULT 10000

)
ALTER TABLE dbo.PHIEUTHUTIEN ADD CONSTRAINT FK_PTT_KH FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG (MAKH)
GO
ALTER TABLE HOADON ADD CONSTRAINT F_K_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
GO
ALTER TABLE SACH ADD CONSTRAINT F_K_SACH_LAOISACH FOREIGN KEY (MALOAISACH) REFERENCES LOAISACH (MALOAISACH)
GO
ALTER TABLE SACH ADD CONSTRAINT F_K_SACH_NXB FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN (MANXB)
GO
ALTER TABLE CTHOADON ADD CONSTRAINT F_K_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD)
GO
ALTER TABLE CTHOADON ADD CONSTRAINT F_K_CTHD_SACH FOREIGN KEY (MASACH) REFERENCES SACH (MASACH)
GO
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT F_K_CTPN_PNS FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAPSACH (MAPHIEUNHAP)
GO
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT F_K_CTPN_SACH FOREIGN KEY (MASACH) REFERENCES SACH 
 GO

 INSERT	dbo.TAIKHOAN
 (
     TENTK,
     MATKHAU,
     TENHIENTHI,
     HINHANH,
     LOAITK
 )
 VALUES
 (   N'Admin',  -- TENTK - nvarchar(30)
     '1234',   -- MATKHAU - char(30)
     N'Admin',  -- TENHIENTHI - nvarchar(50)
     NULL, -- HINHANH - image
     0     -- LOAITK - int
 )
--DANH SÁCH CÁC TRIGGER:
GO
ALTER TABLE dbo.PHIEUNHAPSACH ALTER COLUMN TONGCHI MONEY 

--1 CẬP NHẬT THUỘC TÍNH THÀNH TIỀN TRONG CTPHIEUNHAP
CREATE TRIGGER UPDATE_THANHTIEN
ON dbo.CTPHIEUNHAP
FOR INSERT,UPDATE
AS
BEGIN
	UPDATE dbo.CTPHIEUNHAP SET THANHTIEN = SOLUONG*DONGIA
END 

GO
--2 CẬP NHẬT GIÁ TRỊ TỔNG CHI TRONG BẢNG PHIEUTHU

CREATE TRIGGER UPDATE_TONGCHI
ON dbo.CTPHIEUNHAP
FOR INSERT,UPDATE
AS
BEGIN
	DECLARE @MAPHIEUNHAP INT
	DECLARE @TONGTIEN MONEY

	SELECT @MAPHIEUNHAP = MAPHIEUNHAP FROM Inserted
	
	SELECT @TONGTIEN = SUM(THANHTIEN) FROM dbo.CTPHIEUNHAP WHERE MAPHIEUNHAP = @MAPHIEUNHAP
	IF(@TONGTIEN IS NULL)
		SET @TONGTIEN = 0
	UPDATE dbo.PHIEUNHAPSACH SET TONGCHI = @TONGTIEN WHERE MAPHIEUNHAP = @MAPHIEUNHAP

END 
GO

GO
CREATE TRIGGER UPDATE_SOLUONG
ON dbo.CTPHIEUNHAP
FOR INSERT,UPDATE
AS
BEGIN
	DECLARE @MAPN INT
	DECLARE @MASACH CHAR(5)
	DECLARE @SOLUONG INT
	DECLARE @SOLGTHEM INT

	SELECT @MASACH = Inserted.MASACH,@SOLUONG = Inserted.SOLUONG FROM Inserted
	IF EXISTS(SELECT 1 FROM Deleted)
		SELECT @SOLGTHEM = @SOLUONG - Deleted.SOLUONG FROM Deleted
	ELSE
		SET @SOLGTHEM = @SOLUONG

	IF(@SOLGTHEM<0)
		SET @SOLGTHEM = -@SOLGTHEM

	UPDATE dbo.SACH SET SOLUONGHIENTAI = SOLUONGHIENTAI+@SOLGTHEM WHERE MASACH = @MASACH

END 
GO


--3. CẬP NHẬT ĐƠN GIÁ TRONG BẢNG CT HÓA ĐƠN
CREATE TRIGGER UPDATE_THANHTIEN_CTHOADON
ON dbo.CTHOADON
FOR INSERT,UPDATE
AS
BEGIN
	UPDATE dbo.CTHOADON SET THANHTIEN = SOLUONG*GIABAN
END 
GO

CREATE TRIGGER UPDATE_TONGTIEN
ON dbo.CTHOADON
FOR INSERT,UPDATE
AS
BEGIN
	DECLARE @SOHD INT
	DECLARE @TONGTIEN MONEY

	SELECT @SOHD = Inserted.SOHD FROM Inserted
	
	SELECT @TONGTIEN = SUM(THANHTIEN) FROM dbo.CTHOADON WHERE @SOHD = @SOHD
	IF(@TONGTIEN IS NULL)
		SET @TONGTIEN = 0
	UPDATE dbo.HOADON SET TONGTIEN = @TONGTIEN WHERE SOHD = @SOHD

END 

GO
-- CẬP NHẬT SỐ LƯỢNG SÁCH SAU KHI BÁN
CREATE TRIGGER UPDATE_SOLUONG_ON_SACH_FROM_CTHOADON
ON dbo.CTHOADON
FOR INSERT,UPDATE
AS
BEGIN
	DECLARE @MAPN INT
	DECLARE @MASACH CHAR(5)
	DECLARE @SOLUONG INT
	DECLARE @SOLGGIAM INT

	SELECT @MASACH = Inserted.MASACH,@SOLUONG = Inserted.SOLUONG FROM Inserted
	IF EXISTS(SELECT 1 FROM Deleted)
		SELECT @SOLGGIAM = @SOLUONG - Deleted.SOLUONG FROM Deleted
	ELSE
		SET @SOLGGIAM = @SOLUONG

	IF(@SOLGGIAM<0)
		SET @SOLGGIAM = -@SOLGGIAM

	UPDATE dbo.SACH SET SOLUONGHIENTAI = SOLUONGHIENTAI-@SOLGGIAM WHERE MASACH = @MASACH

END 

--Update sách sau khi insert
GO
CREATE TRIGGER ADD_DEFAULT_SOLUONGSACH
ON dbo.SACH
FOR INSERT
AS
BEGIN
	DECLARE @MASACH CHAR(5)
	SELECT @MASACH = Inserted.MASACH FROM Inserted
    UPDATE dbo.SACH SET SOLUONGHIENTAI = 0 WHERE MASACH = @MASACH
END
GO

--update tiền thừa và tiền nợ
CREATE TRIGGER UPDATE_TIENTHUA_TIENNO
ON dbo.PHIEUTHUTIEN
FOR INSERT
AS
BEGIN
    DECLARE @MAPT CHAR(5)
	DECLARE @TIENTHU MONEY
	DECLARE @TIENNO MONEY
	DECLARE @MAKH CHAR(5)
	SELECT @MAPT = Inserted.MAPT,@TIENTHU = Inserted.TIENTHU,@MAKH = Inserted.MAKH FROM Inserted
	SELECT @TIENNO = TIENNO FROM dbo.KHACHHANG WHERE MAKH = @MAKH
	IF(@TIENTHU >= @TIENNO)
		BEGIN
		    UPDATE dbo.PHIEUTHUTIEN SET TIENNO = 0,TIENTHUA = @TIENTHU - @TIENNO WHERE MAPT = @MAPT
			UPDATE dbo.KHACHHANG SET TIENNO = 0 WHERE MAKH = @MAKH
		END
	ELSE
		BEGIN
		    UPDATE dbo.PHIEUTHUTIEN SET TIENNO = @TIENNO - @TIENTHU,TIENTHUA = 0 WHERE MAPT = @MAPT
			UPDATE dbo.KHACHHANG SET TIENNO = TIENNO - @TIENTHU WHERE MAKH = @MAKH
		END
		
END
GO
CREATE TRIGGER TG_ADD_DEFAULTVALUE
ON dbo.KHACHHANG
FOR INSERT
AS
BEGIN
	DECLARE @MaKH CHAR(5)
	SELECT @MaKH = MAKH FROM Inserted
    UPDATE dbo.KHACHHANG SET TIENNO = 0 WHERE MAKH = @MaKH
END

GO
CREATE TRIGGER UPDATE_TIENNO_FROM_HOADON
ON dbo.HOADON
FOR UPDATE
AS
BEGIN
    DECLARE @MAKH CHAR(5)
	DECLARE @HDTIENNO MONEY
	SELECT @MAKH = Inserted.MAKH,@HDTIENNO = Inserted.TONGTIEN - Inserted.TIENNHAN FROM Inserted
	IF(@HDTIENNO>0)
		UPDATE dbo.KHACHHANG SET TIENNO = TIENNO + @HDTIENNO WHERE MAKH = @MAKH
END
GO

--STORE PROCEDURE

CREATE PROCEDURE USP_BAOCAODOANHTHU
@Date DATE
AS
BEGIN
	SELECT KHACHHANG.MAKH, KHACHHANG.TENKH,SUM(TONGTIEN) AS 'Doanh Thu' FROM KHACHHANG,HOADON,CTHOADON 
	WHERE HOADON.MAKH = KHACHHANG.MAKH AND HOADON.SOHD = CTHOADON.SOHD AND MONTH(HOADON.NGAYHD) = MONTH(@Date) AND YEAR(HOADON.NGAYHD) = YEAR(@Date) 
	GROUP BY KHACHHANG.MAKH,KHACHHANG.TENKH
END
GO
CREATE PROC USP_BAOCAOCHIPHI
@Date Date
AS
BEGIN
    SELECT CONVERT(Date,NGAYNHAP) AS 'Ngày Nhập' ,SUM(TONGCHI) AS 'Tong Chi' FROM PHIEUNHAPSACH WHERE MONTH(NGAYNHAP) = MONTH(@Date) AND YEAR(NGAYNHAP) = YEAR(@Date)
	GROUP BY CONVERT(Date,NGAYNHAP)
END
GO

CREATE PROC USP_SACHBANCHAYTRONGTHANG
AS
BEGIN
    SELECT TOP 3 dbo.SACH.MASACH AS SoLuongBan FROM dbo.SACH,dbo.HOADON,dbo.CTHOADON WHERE CTHOADON.MASACH = SACH.MASACH AND CTHOADON.SOHD = HOADON.SOHD
	AND MONTH(NGAYHD) = MONTH(GETDATE()) AND YEAR(NGAYHD) = YEAR(GETDATE())
	GROUP BY SACH.MASACH ORDER BY SUM(SOLUONG) DESC
END
DROP PROC dbo.USP_SACHBANCHAYTRONGTHANG
GO
CREATE PROC USP_DOANHTHUSACHTRONGTHANG
AS
BEGIN
    SELECT TOP 3 SACH.MASACH,TENSACH,SUM(THANHTIEN) AS TONGTIEN FROM dbo.SACH,dbo.HOADON,dbo.CTHOADON WHERE CTHOADON.MASACH = SACH.MASACH AND CTHOADON.SOHD = HOADON.SOHD
	AND MONTH(NGAYHD) = MONTH(GETDATE()) AND YEAR(NGAYHD) = YEAR(GETDATE())
	GROUP BY SACH.MASACH,TENSACH ORDER BY SUM(THANHTIEN) DESC
END
------------------------------------------------------------------------------
--
--
--						NO NEED TO USE RIGHT NOW
--
--
------------------------------------------------------------------------------
