drop database QUAN_LI_NHA_SACH
CREATE DATABASE QUAN_LI_NHA_SACH
GO
USE QUAN_LI_NHA_SACH
GO
CREATE TABLE KHACHHANG(
MAKH INT NOT NULL,
MALOAIKH INT,
TENKH NVARCHAR(40),
GIOITINH NVARCHAR(20),
DIACHI NVARCHAR(50),
CMND CHAR(20),
NGAYDK DATETIME,
DIEMTICHLUY INT
PRIMARY KEY (MAKH))

GO
CREATE TABLE LOAIKH(
MALOAIKH INT,
TENLOAIKH NVARCHAR(40)
PRIMARY KEY (MALOAIKH))


GO
CREATE TABLE HOADON(
SOHD INT,
MAKH INT,
MANV INT,
NGAYHD DATETIME,
TONGTIEN MONEY,
SOTIENNHAN MONEY,
SOTIENTHUA MONEY
PRIMARY KEY (SOHD))

GO
CREATE TABLE KHUYENMAI(
MAKM INT,
TENKM NVARCHAR(40),
NGAYBD DATETIME,
NGAYKT DATETIME
PRIMARY KEY (MAKM))

GO
CREATE TABLE CTKHUYENMAI(
MAKM INT,
MALOAIKH INT,
MALOAISACH INT,
SOLUONGGIAM INT,
GHICHU NVARCHAR(100)
PRIMARY KEY (MAKM, MALOAIKH, MALOAISACH))

GO
CREATE TABLE LOAISACH(
MALOAISACH INT,
TENLOAISACH NVARCHAR(30),
CHUDE NVARCHAR(30)
PRIMARY KEY (MALOAISACH))

GO
CREATE TABLE SACH(
MASACH INT,
TENSACH NVARCHAR(30),
MALOAISACH INT,
MATACGIA INT,
NXB INT,
SOLUONGHIENTAI INT,
DONGIA MONEY,
NOIDUNG NVARCHAR(100)
PRIMARY KEY (MASACH))

GO
CREATE TABLE CTHOADON(
SOHD INT,
MASACH INT,
SOLUONG INT,
DONGIA MONEY
PRIMARY KEY (SOHD, MASACH))

GO
CREATE TABLE NHANVIEN(
MANV INT,
TENNV NVARCHAR(30),
NGAYSINH DATETIME,
DIACHI NVARCHAR(50),
NGAYVL DATETIME
PRIMARY KEY (MANV))

GO
CREATE TABLE LUONG(
MALUONG INT,
LUONGCOBAN MONEY,
HESO INT
PRIMARY KEY (MALUONG))

GO
CREATE TABLE CTLUONG(
MANV INT,
MALUONG INT,
NGAYPHAT DATETIME,
LUONG MONEY
PRIMARY KEY (MANV, MALUONG))

GO
CREATE TABLE BAOCAOTHANG(
SOBAOCAO INT,
MANV INT,
TONGDOANHTHU MONEY,
NGAYBAOCAO DATETIME,
GHICHU NVARCHAR(100)
PRIMARY KEY (SOBAOCAO))

GO
CREATE TABLE CTBAOCAO(
SOBAOCAO INT,
MASACH INT,
SOLUONGBAN INT,
GIABAN MONEY,
DOANHTHU MONEY
PRIMARY KEY (SOBAOCAO, MASACH))
GO
CREATE TABLE PHIEUNHAPSACH(
MAPHIEUNHAP INT,
MANV INT,
TONGCHI MONEY, 
NGAYNHAP DATETIME
PRIMARY KEY (MAPHIEUNHAP))
GO
CREATE TABLE CTPHIEUNHAP(
MAPHIEUNHAP INT,
MASACH INT,
SOLUONG INT,
DONGIA MONEY
PRIMARY KEY (MAPHIEUNHAP, MASACH))
GO
CREATE TABLE NHAXUATBAN(
MANXB INT,
TENNXB NVARCHAR(30),
DIACHI NVARCHAR(50)
PRIMARY KEY (MANXB))
GO
CREATE TABLE TACGIA(
MATACGIA INT,
TENTACGIA NVARCHAR(30)
PRIMARY KEY (MATACGIA))

ALTER TABLE KHACHHANG ADD CONSTRAINT F_K_KH_LOAIKH FOREIGN KEY (MALOAIKH) REFERENCES LOAIKH (MALOAIKH)
GO
ALTER TABLE HOADON ADD CONSTRAINT F_K_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)
GO

ALTER TABLE CTKHUYENMAI ADD CONSTRAINT F_K_CTKM_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI (MAKM)
GO
ALTER TABLE CTKHUYENMAI ADD CONSTRAINT F_K_CTKM_LOAIKH FOREIGN KEY (MALOAIKH) REFERENCES LOAIKH (MALOAIKH)
GO
ALTER TABLE CTKHUYENMAI ADD CONSTRAINT F_K_CTKM_LOAISACH FOREIGN KEY (MALOAISACH) REFERENCES LOAISACH (MALOAISACH)
GO
ALTER TABLE SACH ADD CONSTRAINT F_K_SACH_LAOISACH FOREIGN KEY (MALOAISACH) REFERENCES LOAISACH (MALOAISACH)
GO
ALTER TABLE SACH ADD CONSTRAINT F_K_SACH_TACGIA FOREIGN KEY (MATACGIA) REFERENCES TACGIA (MATACGIA)
GO
ALTER TABLE SACH ADD CONSTRAINT F_K_SACH_NXB FOREIGN KEY (NXB) REFERENCES NHAXUATBAN (MANXB)
GO
ALTER TABLE CTHOADON ADD CONSTRAINT F_K_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD)
GO
ALTER TABLE CTHOADON ADD CONSTRAINT F_K_CTHD_SACH FOREIGN KEY (MASACH) REFERENCES SACH (MASACH)
GO
ALTER TABLE CTLUONG ADD CONSTRAINT F_K_CTLUONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
GO
ALTER TABLE CTLUONG ADD CONSTRAINT F_K_CTLUONG_LUONG FOREIGN KEY (MALUONG) REFERENCES LUONG (MALUONG)
GO
ALTER TABLE BAOCAOTHANG ADD CONSTRAINT F_K_BCT_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
GO
ALTER TABLE CTBAOCAO ADD CONSTRAINT F_K_CTBC_BCT FOREIGN KEY (SOBAOCAO) REFERENCES BAOCAOTHANG (SOBAOCAO)
GO
ALTER TABLE CTBAOCAO ADD CONSTRAINT F_K_CTBC_SACH FOREIGN KEY (MASACH) REFERENCES SACH (MASACH)
GO
ALTER TABLE PHIEUNHAPSACH ADD CONSTRAINT F_K_PNS_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
GO
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT F_K_CTPN_PNS FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAPSACH (MAPHIEUNHAP)
GO
ALTER TABLE CTPHIEUNHAP ADD CONSTRAINT F_K_CTPN_SACH FOREIGN KEY (MASACH) REFERENCES SACH 
 GO

 --TAO TRIGGER DIEMTICHLUY >= 0
 CREATE TRIGGER INSERT_UPDATE
 ON KHACHHANG
 FOR INSERT, UPDATE
 AS
 DECLARE @DIEMTICHLUY INT
 SELECT @DIEMTICHLUY = DIEMTICHLUY FROM inserted
 IF(@DIEMTICHLUY < 0)
 BEGIN
 PRINT'DIEM TICH LUY PHAI LON HON HOAC BANG 0'
 ROLLBACK TRAN
 END
 GO


 --TẠO CHECK CHO LOẠI KHÁCH HÀNG
 ALTER TABLE LOAIKH 
 ADD CONSTRAINT CKECK_TENLOAIKH CHECK (TENLOAIKH  IN ('THUONG' , 'VIP'))
 GO

 --TẠO TRIGGER CHO HOADON: NGAYHD>= NGAYDK
 CREATE TRIGGER HD_NGAYHD_NGAYDK 
 ON HOADON
 FOR INSERT, UPDATE
 AS
 DECLARE @NGAYHD DATETIME, @MAKH INT, @NGAYDK DATETIME
 SELECT @MAKH = MAKH, @NGAYHD = NGAYHD
 FROM INSERTED 
 SELECT @NGAYDK = NGAYDK
 FROM KHACHHANG
 WHERE MAKH = @MAKH
 IF(@NGAYHD < @NGAYDK)
 BEGIN
 PRINT'NGAY HOA DON KHONG DUOC NHO HON NGAY DANG KI KHACH HANG'
 ROLLBACK TRAN
 END
 GO

 --TẠO TRIGGER CHO BANG KHACHHANG: NGAYDK <= NGAYHD
 CREATE TRIGGER KH_NGAYDK_NGAYHD
 ON KHACHHANG
 FOR UPDATE
 AS
 IF UPDATE(NGAYDK)
 BEGIN
 DECLARE @MAKH INT, @NGAYDK DATETIME
 SELECT @MAKH = MAKH, @NGAYDK = NGAYDK
 FROM INSERTED 
 IF(SELECT COUNT(*) FROM HOADON 
	WHERE @MAKH = MAKH
	AND NGAYHD < @NGAYDK) > 0
	BEGIN
	PRINT'NGAY DANG KI KHONG DUOC LON HON NGAY HOA DON'
	ROLLBACK TRAN
	END
 END
 GO

--TẠO TRIGGER CHO BẢNG NHANVIEN: NGAYVL<= NGAYHD
ALTER TRIGGER NHANVIEN_NGAYVL_NGAYHD
ON NHANVIEN
FOR UPDATE
AS
IF UPDATE(NGAYVL)
BEGIN
DECLARE @MANV INT, @NGAYVL DATETIME
SELECT @MANV = MANV, @NGAYVL = NGAYVL
FROM INSERTED 
IF(SELECT COUNT(*) FROM HOADON
	WHERE @MANV = MANV
	AND @NGAYVL > NGAYHD) > 0
	BEGIN
	PRINT'NGAY NHAN VIEN VAO LAM KHONG DUOC LON HON NGAY HOA DON'
	ROLLBACK TRAN
	END
END
GO
--TẠO TRIGGER CHO BẢNG HOADON: NGAYHD >= NGAYVL
CREATE TRIGGER HD_NGAYHD_NGAYVL
ON HOADON
FOR INSERT, UPDATE
AS
DECLARE @MANV INT, @NGAYHD DATETIME, @NGAYVL DATETIME
SELECT @MANV = MANV, @NGAYHD = NGAYHD
FROM INSERTED 
SELECT @NGAYVL = NGAYVL
FROM NHANVIEN
WHERE MANV = @MANV
IF(@NGAYHD < @NGAYVL)
BEGIN
PRINT'NGAY HOA DON KHONG DUOC NHO HON NGAY VAO LAM CUA NHAN VIEN'
END
GO

--xem thông tin và lương của 1 nhân viên
CREATE PROCEDURE TIM_NHANVIEN
@MNV INT
AS
BEGIN
SELECT NV.MANV, TENNV, NGAYSINH, DIACHI, NGAYVL, L.LUONG
FROM NHANVIEN NV, CTLUONG L
WHERE NV.MANV = @MNV
END
GO

--xem tổng tiền của 1 khách hàng đã mua
CREATE FUNCTION TONGTIEN_KHACHHANG( @MAKH INT )
RETURNS MONEY
AS
BEGIN
DECLARE @LUONG MONEY
SELECT @LUONG = SUM(TONGTIEN)
FROM HOADON
WHERE @MAKH IN (SELECT MAKH
				FROM HOADON
				WHERE @MAKH = MAKH)
RETURN @LUONG
END
GO
--xem thông tin của 1 khách hàng
